//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EoL_Automatik_Ladetest.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EoL_Automatik_Ladetest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 Mal, 1 Minute ähnelt.
        /// </summary>
        internal static string _3m1m {
            get {
                return ResourceManager.GetString("3m1m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 Mal, 5 Minuten ähnelt.
        /// </summary>
        internal static string _3m5m {
            get {
                return ResourceManager.GetString("3m5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LadeTestBericht ähnelt.
        /// </summary>
        internal static string bericht {
            get {
                return ResourceManager.GetString("bericht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC1 ähnelt.
        /// </summary>
        internal static string DC1 {
            get {
                return ResourceManager.GetString("DC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC1 Isolationsprüfung ähnelt.
        /// </summary>
        internal static string DC1IsoTest {
            get {
                return ResourceManager.GetString("DC1IsoTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC1 Ladetest ähnelt.
        /// </summary>
        internal static string DC1LadeTest {
            get {
                return ResourceManager.GetString("DC1LadeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC2 ähnelt.
        /// </summary>
        internal static string DC2 {
            get {
                return ResourceManager.GetString("DC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC2 Isolationsprüfung ähnelt.
        /// </summary>
        internal static string DC2IsoTest {
            get {
                return ResourceManager.GetString("DC2IsoTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC2 Ladetest ähnelt.
        /// </summary>
        internal static string DC2LadeTest {
            get {
                return ResourceManager.GetString("DC2LadeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ergebnis ähnelt.
        /// </summary>
        internal static string ergebnis {
            get {
                return ResourceManager.GetString("ergebnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alles Tests ähnelt.
        /// </summary>
        internal static string m_alleTests {
            get {
                return ResourceManager.GetString("m_alleTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigt ähnelt.
        /// </summary>
        internal static string m_bestaetigt {
            get {
                return ResourceManager.GetString("m_bestaetigt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ist bestanden ähnelt.
        /// </summary>
        internal static string m_bestanden {
            get {
                return ResourceManager.GetString("m_bestanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ist nicht bestanden ähnelt.
        /// </summary>
        internal static string m_bestandenNicht {
            get {
                return ResourceManager.GetString("m_bestandenNicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Verbindung mit dem CDS wurde verloren ähnelt.
        /// </summary>
        internal static string m_cdsConectionLost {
            get {
                return ResourceManager.GetString("m_cdsConectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Programm ist richtig mit dem CDS verbunden. ähnelt.
        /// </summary>
        internal static string m_cdsConnected {
            get {
                return ResourceManager.GetString("m_cdsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CDS ist im Fehler. Bitte beheben Sie den Fehler und versuchen nochmal. ähnelt.
        /// </summary>
        internal static string m_CdsFehler {
            get {
                return ResourceManager.GetString("m_CdsFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Programm ist mit dem CDS nitch verbunden. Bitte versuchen Sie die Verbindung zu erreichen und dann starten Sie den Test nochmal. ähnelt.
        /// </summary>
        internal static string m_cdsNotConnected {
            get {
                return ResourceManager.GetString("m_cdsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die endet. ähnelt.
        /// </summary>
        internal static string m_endet {
            get {
                return ResourceManager.GetString("m_endet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Flags lesen ähnelt.
        /// </summary>
        internal static string m_errorFlagsLesen {
            get {
                return ResourceManager.GetString("m_errorFlagsLesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn der Charger wieder grün ist, clicken Sie bitte auf JA ähnelt.
        /// </summary>
        internal static string m_f_chargerGruen {
            get {
                return ResourceManager.GetString("m_f_chargerGruen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind Error FLags richtig? ähnelt.
        /// </summary>
        internal static string m_f_errorFlagsLesen {
            get {
                return ResourceManager.GetString("m_f_errorFlagsLesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ist der Test bestanden? ähnelt.
        /// </summary>
        internal static string m_f_istBestanden {
            get {
                return ResourceManager.GetString("m_f_istBestanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haben Sie die Ladepistole angestecket? ähnelt.
        /// </summary>
        internal static string m_f_LadePistgesteckt {
            get {
                return ResourceManager.GetString("m_f_LadePistgesteckt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte drücken Sie das Notausknopf ähnelt.
        /// </summary>
        internal static string m_notausDruecken {
            get {
                return ResourceManager.GetString("m_notausDruecken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte normalizieren das Notausknopf. ähnelt.
        /// </summary>
        internal static string m_NotausNormailizieren {
            get {
                return ResourceManager.GetString("m_NotausNormailizieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF wurde erfolgreich erstellt ähnelt.
        /// </summary>
        internal static string m_PDFerstellt {
            get {
                return ResourceManager.GetString("m_PDFerstellt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Erstellung des PDF-Bericht ist jetzt verfügbar.  ähnelt.
        /// </summary>
        internal static string m_PDverfugbar {
            get {
                return ResourceManager.GetString("m_PDverfugbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicher PDF als ähnelt.
        /// </summary>
        internal static string m_SpeichernAlsPDF {
            get {
                return ResourceManager.GetString("m_SpeichernAlsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starten ähnelt.
        /// </summary>
        internal static string m_starten {
            get {
                return ResourceManager.GetString("m_starten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Test wurde gestopet ähnelt.
        /// </summary>
        internal static string m_testStopt {
            get {
                return ResourceManager.GetString("m_testStopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte machen Sie die Tür wieder zu. ähnelt.
        /// </summary>
        internal static string m_tuerNormalisieren {
            get {
                return ResourceManager.GetString("m_tuerNormalisieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte öffnen Sie die Tür ähnelt.
        /// </summary>
        internal static string m_tuerOeffnen {
            get {
                return ResourceManager.GetString("m_tuerOeffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode: Automatik ähnelt.
        /// </summary>
        internal static string mode_automatik {
            get {
                return ResourceManager.GetString("mode_automatik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode: Wartung ähnelt.
        /// </summary>
        internal static string mode_wartung {
            get {
                return ResourceManager.GetString("mode_wartung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notaustest ähnelt.
        /// </summary>
        internal static string notAusTest {
            get {
                return ResourceManager.GetString("notAusTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Türkontakttest ähnelt.
        /// </summary>
        internal static string tuerKontaktTest {
            get {
                return ResourceManager.GetString("tuerKontaktTest", resourceCulture);
            }
        }
    }
}
