//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EoL_Automatik_Ladetest.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EoL_Automatik_Ladetest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 x 1 Minute ähnelt.
        /// </summary>
        internal static string _3m1m {
            get {
                return ResourceManager.GetString("3m1m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 x 5 Minuten ähnelt.
        /// </summary>
        internal static string _3m5m {
            get {
                return ResourceManager.GetString("3m5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatik ähnelt.
        /// </summary>
        internal static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ladetest-Protokoll ähnelt.
        /// </summary>
        internal static string bericht {
            get {
                return ResourceManager.GetString("bericht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CDS Status ähnelt.
        /// </summary>
        internal static string cdsStatus {
            get {
                return ResourceManager.GetString("cdsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC1 ähnelt.
        /// </summary>
        internal static string DC1 {
            get {
                return ResourceManager.GetString("DC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC1 Isolationsprüfung ähnelt.
        /// </summary>
        internal static string DC1IsoTest {
            get {
                return ResourceManager.GetString("DC1IsoTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC1 Ladetest ähnelt.
        /// </summary>
        internal static string DC1LadeTest {
            get {
                return ResourceManager.GetString("DC1LadeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC2 ähnelt.
        /// </summary>
        internal static string DC2 {
            get {
                return ResourceManager.GetString("DC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC2 Isolationsprüfung ähnelt.
        /// </summary>
        internal static string DC2IsoTest {
            get {
                return ResourceManager.GetString("DC2IsoTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DC2 Ladetest ähnelt.
        /// </summary>
        internal static string DC2LadeTest {
            get {
                return ResourceManager.GetString("DC2LadeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string einstellungen {
            get {
                return ResourceManager.GetString("einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ergebnis ähnelt.
        /// </summary>
        internal static string ergebnis {
            get {
                return ResourceManager.GetString("ergebnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtergebnis:  ähnelt.
        /// </summary>
        internal static string m_alleTests {
            get {
                return ResourceManager.GetString("m_alleTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigt ähnelt.
        /// </summary>
        internal static string m_bestaetigt {
            get {
                return ResourceManager.GetString("m_bestaetigt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bestanden ähnelt.
        /// </summary>
        internal static string m_bestanden {
            get {
                return ResourceManager.GetString("m_bestanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nicht bestanden ähnelt.
        /// </summary>
        internal static string m_bestandenNicht {
            get {
                return ResourceManager.GetString("m_bestandenNicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CDS Verbindung ist getrennt ähnelt.
        /// </summary>
        internal static string m_cdsConnected {
            get {
                return ResourceManager.GetString("m_cdsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messequipment hat ein oder mehrere Fehler. Bitte beheben Sie die Fehler und versuchen es nochmal. ähnelt.
        /// </summary>
        internal static string m_CdsFehler {
            get {
                return ResourceManager.GetString("m_CdsFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Programm ist mit dem CDS nitch verbunden. Bitte versuchen Sie die Verbindung zu erreichen und dann starten Sie den Test nochmal. ähnelt.
        /// </summary>
        internal static string m_cdsNotConnected {
            get {
                return ResourceManager.GetString("m_cdsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ist beendet ähnelt.
        /// </summary>
        internal static string m_endet {
            get {
                return ResourceManager.GetString("m_endet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn der Charger wieder Ladebereit ist, bestätigen Sie Bitte mit Ja. ähnelt.
        /// </summary>
        internal static string m_f_chargerGruen {
            get {
                return ResourceManager.GetString("m_f_chargerGruen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Flags kontrollieren ähnelt.
        /// </summary>
        internal static string m_f_errorFlagsLesen {
            get {
                return ResourceManager.GetString("m_f_errorFlagsLesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind die Ladepistolen Richtig verbunden ähnelt.
        /// </summary>
        internal static string m_f_LadePistgesteckt {
            get {
                return ResourceManager.GetString("m_f_LadePistgesteckt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte betätigen Sie jetzt den Not-Aus am Charger ähnelt.
        /// </summary>
        internal static string m_notausDruecken {
            get {
                return ResourceManager.GetString("m_notausDruecken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte setzen Sie den Not-Aus am Charger zurück ähnelt.
        /// </summary>
        internal static string m_NotausNormailizieren {
            get {
                return ResourceManager.GetString("m_NotausNormailizieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ladetest-Protokoll wurde erstellt ähnelt.
        /// </summary>
        internal static string m_PDFerstellt {
            get {
                return ResourceManager.GetString("m_PDFerstellt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ladetest-Protokoll kann erstellt werden ähnelt.
        /// </summary>
        internal static string m_PDverfugbar {
            get {
                return ResourceManager.GetString("m_PDverfugbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ladetest-Protokoll speichern unter ähnelt.
        /// </summary>
        internal static string m_SpeichernAlsPDF {
            get {
                return ResourceManager.GetString("m_SpeichernAlsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die starten ähnelt.
        /// </summary>
        internal static string m_starten {
            get {
                return ResourceManager.GetString("m_starten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Test wurde abgebrochen ähnelt.
        /// </summary>
        internal static string m_testStopt {
            get {
                return ResourceManager.GetString("m_testStopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte schließen Sie die Charger Tür ähnelt.
        /// </summary>
        internal static string m_tuerNormalisieren {
            get {
                return ResourceManager.GetString("m_tuerNormalisieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte öffnen Sie jetzt die Charger Tür ähnelt.
        /// </summary>
        internal static string m_tuerOeffnen {
            get {
                return ResourceManager.GetString("m_tuerOeffnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prüffeld ähnelt.
        /// </summary>
        internal static string menuPF {
            get {
                return ResourceManager.GetString("menuPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prüffelder IP-Adresse ähnelt.
        /// </summary>
        internal static string menuPF_IP {
            get {
                return ResourceManager.GetString("menuPF_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode: Automatik ähnelt.
        /// </summary>
        internal static string mode_automatik {
            get {
                return ResourceManager.GetString("mode_automatik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode: Wartung ähnelt.
        /// </summary>
        internal static string mode_wartung {
            get {
                return ResourceManager.GetString("mode_wartung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notaus ähnelt.
        /// </summary>
        internal static string notaus {
            get {
                return ResourceManager.GetString("notaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notaustest ähnelt.
        /// </summary>
        internal static string notAusTest {
            get {
                return ResourceManager.GetString("notAusTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prüffeld wählen ähnelt.
        /// </summary>
        internal static string pfWaehlen {
            get {
                return ResourceManager.GetString("pfWaehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ladetest-Protokoll erstellen ähnelt.
        /// </summary>
        internal static string protokollErstellen {
            get {
                return ResourceManager.GetString("protokollErstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seriennummer ähnelt.
        /// </summary>
        internal static string serienNummer {
            get {
                return ResourceManager.GetString("serienNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STARTEN ähnelt.
        /// </summary>
        internal static string starten {
            get {
                return ResourceManager.GetString("starten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STOPPEN ähnelt.
        /// </summary>
        internal static string stoppen {
            get {
                return ResourceManager.GetString("stoppen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tests ähnelt.
        /// </summary>
        internal static string tests {
            get {
                return ResourceManager.GetString("tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trennen ähnelt.
        /// </summary>
        internal static string trennen {
            get {
                return ResourceManager.GetString("trennen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Türkontakttest ähnelt.
        /// </summary>
        internal static string tuerKontaktTest {
            get {
                return ResourceManager.GetString("tuerKontaktTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinden ähnelt.
        /// </summary>
        internal static string verbinden {
            get {
                return ResourceManager.GetString("verbinden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindungsstatus ähnelt.
        /// </summary>
        internal static string verbindungsStatus {
            get {
                return ResourceManager.GetString("verbindungsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wartung ähnelt.
        /// </summary>
        internal static string wartung {
            get {
                return ResourceManager.GetString("wartung", resourceCulture);
            }
        }
    }
}
